### ISSUE TITLE
Need to determine what framework/library to use for game function

### ISSUE THREAD

**Issue by cmccormack** [cmccormack/minesweeper#5]
Default options are Vanilla JavaScript, React, Angular, Vue, and Marko.  Other options are welcome for discussion.

**Comment by bradtaniguchi** [comment]
I vote for React (stick with the mainstream) or [PhaserJS](https://phaser.io/) if someone wants to use a game-engine, except we'd have to produce some images/sprites for the elements in the game which adds some graphic work. PhaserJS might be to far out of left-field, but its worth tho mention 😉 

Also, **we should use typescript** regardless of what framework/library we use. 

PS. I know no one wants to learn Angular so I wont suggest it :'(

**Comment by kbaig** [comment]
Markooooooooo.

I'd bootstrap with `create-react-app`. It comes with testing and TypeScript already set up.

**Comment by kbaig** [comment]
I should also add that React has the added benefit of making it easier to port to native using React Natiive

**Comment by bradtaniguchi** [comment]
Currently we are considering using just TS with no framework :)

**Comment by cmccormack** [comment]
React has been added but we still haven't written any actual code so feel free to add justifications for anything else!

**Comment by bradtaniguchi** [comment]
> anything else!

I mean we could use Angular, which I know everyone wants to learn and use 😜

**Comment by kbaig** [comment]
Seeing as we are locking React in, shall we close this?
